### ISSUE TITLE
一些不成熟的建议

### ISSUE THREAD

**Issue by SlenderMongoose** [gusye1234/recad#2]
我今天早上看见 RecSys 上出来了 Rec 攻防的 benchmark ，早饭都没吃看的论文和代码，看完之后是更吃不下了。
你不能说是把陈思的 aush 从 tensorflow 上拉到 torch 上就叫出了一个 benchmark
有如下建议：

攻击部分
攻击最好分开评分和不带评分，因为这俩东西从设计理念到衡量攻击和防御的标准都是很不一样的（除了HR）
传统攻击里可以加 poweruser，poweritem 等攻击，模糊攻击等问题，不要总是随机的选择项目然后依据模板填充分数，这几个合在一起也就是一个 random attack
深度攻击这几年是越来越多，简单协同过滤的就包括 pga copy goat trialattack rapu dl-attack 还有强化学习的 跨系统的跨域的 等一堆，不只是 leg-up
深度造评分的攻击很不好处理，模型动一个参数那评分剧烈波动，两份攻击文件放在一起甚至感觉不出来是来自同样的生成架构。
还有如果要在 ml-100k ml-1m 数据集上通常要同时攻击5个商品，否则可能看不到有效的攻击效果

防御部分
我没看到你们有防御的部分，难道用的还是 sdlib 吗？
曾经针对评分的攻击有一些鲁棒推荐系统，用什么鲁棒估计，可以抑制这种评分的上涨，但现在的鲁棒推荐模型大多防御的自然噪声，因为用的数据集是隐式的。
检测的主要库 sdlib 里存在严重的标签泄露问题，绝对不允许在一个攻击文件上划分训练测试，正确的划分方式可以参考 07 年 Defending recommender systems: detection of profile injection attacks 的方式，但这样的手段在用于深度攻击上构造训练集的代价可能太高。深度的攻击该怎么检到现在也没个标准，有些论文里说能检，然后给一个挺高的数，但代码里从来不给攻击文件，由于生成的不稳定性，谁也不知道对方在检测什么东西。
无监督的检测数更离谱，查出来0.0几都有可能，我扔个硬币查的都比他准，那个 FAP 的结果极大依赖于参数，有的时候 select user 越多甚至效果越差，包括 top 前多少认为是假，这都是问题。
评分攻击有监督检测的还很大程度上抓取的评分模板的特征，不带评分的检测怎么检又是一个问题。
上面的工作掰掰手指还都是5，6年前的，近年的工作已经从离谱走向了魔幻。攻击问题就不少，防御又在它的下游，可以说问题更多、毫无标准，近年有效的工作极少。

我以为您至少把一些难处理的攻击放到了一个整体框架中，或者至少在防御层面搞出一套标准和流程，但现在我看完了，又开始愁毕业了。

**Comment by gusye1234** [comment]
您好, 感谢你的专业斧正和建议. RecAD现在还是很不成熟的状态, 也在测试, 支持更多算法和数据的过程中. 
RecAD的unified更多是指工程层面的, 而非算法层面. 如果有想迫切想要支持的feature或者算法, 希望您可以给出相关的reference或者代码实现, 我们会尽快的添加到model或者workflow里来. 
RecAD希望通过清晰的dataset, model以及workflow的抽象可以去囊括您说的多种“魔幻”的工作, 希望您可以进一步细化你的feature需求, 我们会在之后的commit中提及到这个issue的

**Comment by SlenderMongoose** [comment]
除了你们现在有的这些攻击，下面的攻击github上有代码/他人代码中存在相关代码/极其容易复现
2013 When Power Users Attack: Assessing Impacts in Collaborative Recommender Systems
2014 Attacking Item-Based Recommender Systems with Power Items
2016 Data Poisoning Attacks on Factorization-Based Collaborative Filtering
2019 Adversarial Atacks on an Oblivious Recommender
2021 Data Poisoning Attack against Recommender System Using Incomplete and Perturbed Data
2021 Triple Adversarial Learning for Influence based Poisoning Attack in Recommender Systems
2021 Data Poisoning Attacks to Deep Learning Based Recommender Systems
2023 Practical Cross-System Shilling Attacks with Limited Access to Data
有一些awesome开头的推荐和图攻防的库有更全的攻击和防御的代码指引。从数据集的角度上说，序列推荐上的攻击也可以用这些数据集，这就更多了。

我说的“魔幻”指的是防御和检测的工作，我就是在这个方向上坐牢的，我现在面临的最大困境就是攻击文件生成没有一个标准，检测的数之间比较也没有一个标准，甚至整个流程都是一个问题。早年的传统攻击依据的是评分模板构造，所以只要模板定下来，就可以进行快速高效的测试，两份攻击文件尽管看起来有一些差异，但因为有模板的硬性要求，即便是在不公布攻击文件的情况下，生成的评分、攻击性、隐蔽性也不会波动太大。现在深度攻击的文件生成没一个标准，换两个参数就发生很大变动；且很多检测工作的对比试验依照的是sdlib，且先不说它训练测试的划分有一些问题，我想找一个近三年的工作比一比，我是真找不到，而且很多检测要求的已知不太相同，有一些要求已知一定额外知识比如商品特征等，这使得更换数据集非常麻烦。另外如果是评分攻击最终的指标可以有评分的偏移值，受害推荐系统可以有一些显示的推荐系统和曾经的鲁棒mf。你们现在用的wrmf ncf 都是常见的攻击双层优化中内层的靶系统，这些隐式推荐模型去预测评分还得更改一些东西，aush和leg-up是两种依赖用户模板选取的攻击，整个模型在训练过程中只有评分会发生变动，攻击用户的交互是不会变的，如果用它们来攻击隐式推荐系统，那可能和传统攻击是一样的，即选定模板的一刻就决定了攻击性，都不需要继续跑模型。显式与隐式的转换可能又是另一个问题。

我不太清楚是不是我看漏了，我没有在您的代码中看到防御和检测相关的东西。检测这里依照什么数据检测，曾经工作能查到多少，这些都隶属于这个方向 benchmark 的范围。有监督检测依赖于监督训练集，这个东西在深度投毒下怎么构造是一个问题，因为检测这里不能做成来一份投毒的训练数据，已知一部分查另一部分真假，然后再来一个攻击文件，又已知其中一部分去查另一部分（sdlib就是这个错法）。其实我主要来着看的就是你们用于下游检测和防御的“基准攻击文件”的。另外检测的对比试验我想找一个近三年做一个比较也很费劲，很多检测工作都是在自己叙述的一种特定场景下用着特定的攻击文件查了一个数，还没有代码和使用的攻击文件，复现了一下怎么也和论文中的数对不上，说白了下游的防御/检测任务和攻击文件的构造非常相关。这些工作里还混在着一些查推荐系统群组攻击的，我到现在都不知道这个攻击从哪来的。这就是为什么我说比较魔幻。

我说的这些有很强的个人观点，您可以从这里面挑一些有价值的采纳。我也非常期待您的库。
